# Generated by Django 3.2.5 on 2024-01-26 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_field',
            field=models.URLField(blank=True, null=True),
        ),
    ]
