ARG NODE_VERSION=16.14-alpine

FROM node:14 as node

FROM node as client-local-build

ARG APP_HOME=/app

WORKDIR ${APP_HOME}

COPY ./package*.json .
RUN npm config set registry http://registry.npmjs.org/
RUN npm install


# Expose the port the app runs on
EXPOSE 3000

COPY . ${APP_HOME}

# Run the development server
CMD ["npm", "run", "dev"]